document.writeln("---X---X---X--String Dasar--X---X---X---")
document.writeln("</br>")
document.writeln("Usep Syaikal Arifin")
document.writeln("</br>")
document.writeln("React Js Programmer")
document.writeln("</br>")

document.writeln("---X---X---X--Concantenate String--X---X---X---")
document.writeln("</br>")
document.writeln("Nama : " + "Usep Syaikal Arifin")
document.writeln("</br>")
document.writeln("Skill : " + "React Js Professional")
document.writeln("</br>")

document.writeln("---X---X---X--Escape Sequence--X---X---X---")
document.writeln("</br>")
document.writeln("<textarea cols='100' rows='10'>")
document.write("Usep \nSyaikal \nArifin \n")
document.write("\\Home\\Usep\n")
document.write("\"ReactJs Professional\"\n")
document.write("\'Full Stack Development\'\n")
document.writeln("</textarea>")