let fullName = "Usep Syaikal Arifin"
document.writeln(fullName)
document.writeln("</br>")
document.writeln(fullName)
document.writeln("</br>")
document.writeln(fullName)
document.writeln("</br>")
document.writeln(fullName)
document.writeln("</br>")
document.writeln(fullName)
document.writeln("</br>")
document.writeln(fullName)
document.writeln("</br>")
document.writeln(fullName)
